version: '3.3'

services:
  dgraph:
    image: dgraph/standalone
    container_name: dgrap-container
    volumes: 
      - dgrap:/dgraph
    ports: 
      - "8080:8080"
      - "9080:9080"
    restart: always

  api: 
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - dgraph

volumes:
  dgrap: